name: Publish API documentation

on:
  pull_request:
    paths:
      - ".github/workflows/publish-api-docs.yml"
      - "docs/api/**"
      - "lib/**"
      - "mix.exs"
      - "mix.lock"
  push:
    branches: [main]
    paths:
      - ".github/workflows/publish-api-docs.yml"
      - "docs/api/**"
      - "lib/**"
      - "mix.exs"
      - "mix.lock"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          elixir-version: "1.18.3"
          otp-version: "27.3.4"
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mkdir _site
      - run: mix openapi.spec.json --spec LensWeb.ApiSpec --pretty --start-app=false --filename _site/openapi.json
      - run: cp docs/api/index.html _site/index.html
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: _site

  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: publish-api-documentation
      cancel-in-progress: false
    steps:
      - id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
